# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(575, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(575, 500))
        MainWindow.setMaximumSize(QtCore.QSize(575, 500))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(10)
        font.setBold(True)
        MainWindow.setFont(font)
        MainWindow.setWindowTitle("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/player.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolTip("")
        MainWindow.setStatusTip("")
        MainWindow.setWhatsThis("")
        MainWindow.setAccessibleName("")
        MainWindow.setAccessibleDescription("")
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background: #121212;\n"
"    border-top-right-radius: 10px;\n"
"    border-top-left-radius:  10px;\n"
"}\n"
"*{\n"
"    color: #fff;\n"
"    margin: 0;\n"
"    padding: 0;\n"
"}\n"
"QWidget {\n"
"    background-color: #121212;\n"
"    font-family: Rubik;\n"
"    font-weight: 600;\n"
"}\n"
"QPushButton {\n"
"    border: none;\n"
"}\n"
"QListWidget {\n"
"    border: none;\n"
"    background-color: #121212;\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    outline: none;\n"
"    background: #676767;\n"
"    width: 8px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: #676767;\n"
"}\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    outline: none;\n"
"    background: #676767;\n"
"    height: 8px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: #676767;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: #32CC99;\n"
"    width: 20px;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: #32CC99;\n"
"    width: 20px;\n"
"}\n"
"QScrollBar:left-arrow:horizontal, QScrollBar::right-arrow:horizontal {\n"
"    border: none;\n"
"    background: #121212;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: #999;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: #999;\n"
"}")
        MainWindow.setWindowFilePath("")
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.Main = QtWidgets.QWidget(MainWindow)
        self.Main.setEnabled(True)
        self.Main.setMaximumSize(QtCore.QSize(575, 500))
        self.Main.setStyleSheet("")
        self.Main.setObjectName("Main")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Main)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.image_label = QtWidgets.QLabel(self.Main)
        self.image_label.setMinimumSize(QtCore.QSize(150, 150))
        self.image_label.setMaximumSize(QtCore.QSize(150, 150))
        self.image_label.setStyleSheet("margin: 0;\n"
"border: none;\n"
"background-color: #fff;")
        self.image_label.setText("")
        self.image_label.setIndent(0)
        self.image_label.setObjectName("image_label")
        self.horizontalLayout_2.addWidget(self.image_label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(365, -1, -1, -1)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self._pushButton = QtWidgets.QPushButton(self.Main)
        self._pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self._pushButton.setMaximumSize(QtCore.QSize(30, 30))
        self._pushButton.setStyleSheet("QPushButton:hover {\n"
"    background-color:#353535;\n"
"}")
        self._pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self._pushButton.setIcon(icon1)
        self._pushButton.setIconSize(QtCore.QSize(30, 30))
        self._pushButton.setObjectName("_pushButton")
        self.horizontalLayout_3.addWidget(self._pushButton)
        self.pushButton = QtWidgets.QPushButton(self.Main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton:hover {\n"
"    background-color:#353535;\n"
"}")
        self.pushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon2)
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.track_label = QtWidgets.QLabel(self.Main)
        self.track_label.setMinimumSize(QtCore.QSize(0, 75))
        self.track_label.setMaximumSize(QtCore.QSize(425, 75))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(24)
        font.setBold(True)
        font.setKerning(False)
        self.track_label.setFont(font)
        self.track_label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.track_label.setStyleSheet("font-size: 24pt;\n"
"padding: 0 0 0 10px;")
        self.track_label.setText("")
        self.track_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.track_label.setIndent(0)
        self.track_label.setObjectName("track_label")
        self.verticalLayout.addWidget(self.track_label)
        self.artist_label = QtWidgets.QLabel(self.Main)
        self.artist_label.setMinimumSize(QtCore.QSize(0, 45))
        self.artist_label.setMaximumSize(QtCore.QSize(425, 45))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(10)
        font.setBold(True)
        font.setKerning(False)
        self.artist_label.setFont(font)
        self.artist_label.setStyleSheet("font-size: 10pt;\n"
"padding: 0 0 0 10px;")
        self.artist_label.setText("")
        self.artist_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.artist_label.setObjectName("artist_label")
        self.verticalLayout.addWidget(self.artist_label)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalSlider = QtWidgets.QSlider(self.Main)
        self.horizontalSlider.setMinimumSize(QtCore.QSize(0, 25))
        self.horizontalSlider.setMaximumSize(QtCore.QSize(16777215, 26))
        self.horizontalSlider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider.setStyleSheet("QSlider::handle:horizontal {\n"
"    background: #fff;\n"
"    width: 5px;\n"
"    margin: -2px 0;\n"
"    border: 5px solid #fff;\n"
"    border-radius: 4px;\n"
" }\n"
"QSlider::groove:horizontal {\n"
"    height: 5px;\n"
"    background: #888;\n"
"    margin: 2px 0;\n"
"    border-radius: 2px;\n"
" }")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout_2.addWidget(self.horizontalSlider)
        self.management_menu = QtWidgets.QHBoxLayout()
        self.management_menu.setContentsMargins(2, 4, 2, 4)
        self.management_menu.setSpacing(5)
        self.management_menu.setObjectName("management_menu")
        self.preview_pushButton = QtWidgets.QPushButton(self.Main)
        self.preview_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.preview_pushButton.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(10)
        font.setBold(True)
        self.preview_pushButton.setFont(font)
        self.preview_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.preview_pushButton.setStyleSheet("")
        self.preview_pushButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/back-.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.preview_pushButton.setIcon(icon3)
        self.preview_pushButton.setIconSize(QtCore.QSize(40, 40))
        self.preview_pushButton.setFlat(False)
        self.preview_pushButton.setObjectName("preview_pushButton")
        self.management_menu.addWidget(self.preview_pushButton)
        self.play_pushButton = QtWidgets.QPushButton(self.Main)
        self.play_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.play_pushButton.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(10)
        font.setBold(True)
        self.play_pushButton.setFont(font)
        self.play_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.play_pushButton.setStyleSheet("")
        self.play_pushButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play_pushButton.setIcon(icon4)
        self.play_pushButton.setIconSize(QtCore.QSize(40, 40))
        self.play_pushButton.setFlat(False)
        self.play_pushButton.setObjectName("play_pushButton")
        self.management_menu.addWidget(self.play_pushButton)
        self.next_pushButton = QtWidgets.QPushButton(self.Main)
        self.next_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.next_pushButton.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(10)
        font.setBold(True)
        self.next_pushButton.setFont(font)
        self.next_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.next_pushButton.setStyleSheet("")
        self.next_pushButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/forward+.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next_pushButton.setIcon(icon5)
        self.next_pushButton.setIconSize(QtCore.QSize(40, 40))
        self.next_pushButton.setFlat(False)
        self.next_pushButton.setObjectName("next_pushButton")
        self.management_menu.addWidget(self.next_pushButton)
        self.mute_pushButton = QtWidgets.QPushButton(self.Main)
        self.mute_pushButton.setMinimumSize(QtCore.QSize(25, 25))
        self.mute_pushButton.setMaximumSize(QtCore.QSize(40, 40))
        self.mute_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mute_pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mute_pushButton.setStyleSheet("")
        self.mute_pushButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/volume.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mute_pushButton.setIcon(icon6)
        self.mute_pushButton.setIconSize(QtCore.QSize(40, 40))
        self.mute_pushButton.setObjectName("mute_pushButton")
        self.management_menu.addWidget(self.mute_pushButton)
        self.valume_Slider = QtWidgets.QSlider(self.Main)
        self.valume_Slider.setMinimumSize(QtCore.QSize(100, 25))
        self.valume_Slider.setMaximumSize(QtCore.QSize(100, 25))
        self.valume_Slider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.valume_Slider.setToolTipDuration(-1)
        self.valume_Slider.setStyleSheet("QSlider::handle:horizontal {\n"
"    background: #fff;\n"
"    width: 5px;\n"
"    margin: -2px 0;\n"
"    border: 5px solid #fff;\n"
"    border-radius: 4px;\n"
" }\n"
"QSlider::groove:horizontal {\n"
"    height: 5px;\n"
"    background: #888;\n"
"    margin: 2px 0;\n"
"    border-radius: 2px;\n"
" }")
        self.valume_Slider.setMaximum(100)
        self.valume_Slider.setSingleStep(1)
        self.valume_Slider.setProperty("value", 100)
        self.valume_Slider.setTracking(True)
        self.valume_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.valume_Slider.setInvertedAppearance(False)
        self.valume_Slider.setTickInterval(0)
        self.valume_Slider.setObjectName("valume_Slider")
        self.management_menu.addWidget(self.valume_Slider)
        self.verticalLayout_2.addLayout(self.management_menu)
        self.listWidget = QtWidgets.QListWidget(self.Main)
        self.listWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget.setMaximumSize(QtCore.QSize(16777215, 300))
        self.listWidget.setStyleSheet("")
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.select_btns = QtWidgets.QHBoxLayout()
        self.select_btns.setContentsMargins(-1, 0, 0, 2)
        self.select_btns.setSpacing(0)
        self.select_btns.setObjectName("select_btns")
        self.rand_pushButton = QtWidgets.QPushButton(self.Main)
        self.rand_pushButton.setMaximumSize(QtCore.QSize(40, 40))
        self.rand_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rand_pushButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/random.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rand_pushButton.setIcon(icon7)
        self.rand_pushButton.setIconSize(QtCore.QSize(40, 40))
        self.rand_pushButton.setObjectName("rand_pushButton")
        self.select_btns.addWidget(self.rand_pushButton)
        self.loc_pushButton = QtWidgets.QPushButton(self.Main)
        self.loc_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.loc_pushButton.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(10)
        font.setBold(True)
        self.loc_pushButton.setFont(font)
        self.loc_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loc_pushButton.setStyleSheet("")
        self.loc_pushButton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/select.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loc_pushButton.setIcon(icon8)
        self.loc_pushButton.setIconSize(QtCore.QSize(40, 40))
        self.loc_pushButton.setObjectName("loc_pushButton")
        self.select_btns.addWidget(self.loc_pushButton)
        self.del_pushButton = QtWidgets.QPushButton(self.Main)
        self.del_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.del_pushButton.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(10)
        font.setBold(True)
        self.del_pushButton.setFont(font)
        self.del_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.del_pushButton.setStyleSheet("")
        self.del_pushButton.setText("")
        self.del_pushButton.setIcon(icon1)
        self.del_pushButton.setIconSize(QtCore.QSize(40, 40))
        self.del_pushButton.setObjectName("del_pushButton")
        self.select_btns.addWidget(self.del_pushButton)
        self.clear_pushButton = QtWidgets.QPushButton(self.Main)
        self.clear_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.clear_pushButton.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(10)
        font.setBold(True)
        self.clear_pushButton.setFont(font)
        self.clear_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clear_pushButton.setStyleSheet("")
        self.clear_pushButton.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clear_pushButton.setIcon(icon9)
        self.clear_pushButton.setIconSize(QtCore.QSize(40, 40))
        self.clear_pushButton.setObjectName("clear_pushButton")
        self.select_btns.addWidget(self.clear_pushButton)
        self.verticalLayout_2.addLayout(self.select_btns)
        MainWindow.setCentralWidget(self.Main)

        self.retranslateUi(MainWindow)
        self.listWidget.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.valume_Slider, self.del_pushButton)
        MainWindow.setTabOrder(self.del_pushButton, self.clear_pushButton)

    def retranslateUi(self, MainWindow):
        pass
import resource_rc
